service:
  image: mypi-vscode
  depends: []
  mount:
  - /home/pi/.ssh:/home/pi/.ssh
  - /opt/mypi:/opt/mypi
  - /opt/mypi-tools:/opt/mypi-tools
  - /var/run/docker.sock:/var/run/docker.sock
  - /home/pi:/home/pi
  ports:
  - 2022:22
