#!/usr/bin/env bash

set -e

if ! docker network inspect mypi-ccu &> /dev/null; then
    docker network create -d macvlan --subnet=192.168.0.0/24 --gateway=192.168.0.1 --ip-range 192.168.0.192/27 -o parent=eth0 mypi-ccu
fi
