#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"

if ! docker network inspect mypi-ccu &> /dev/null; then
    docker network create -d macvlan --subnet=192.168.0.0/24 --gateway=192.168.0.1 --ip-range 192.168.0.192/27 -o parent=eth0 mypi-ccu
fi

Service::Start ccu

docker network connect mypi-ccu ccu