service:
  image: ghcr.io/jens-maus/raspberrymatic
  pull: true
  privileged: true
  networks: 
    - mypi-internal
    - mypi-ccu
  mount:
    - /lib/modules:/lib/modules:ro
    - /opt/mypi/data/ccu_data:/usr/local
