FROM postgres:alpine

#RUN apk add --no-cache postgresql openrc

#ENTRYPOINT ["nsd"]
#CMD ["-d"]

#USER postgres

# RUN postgres &\
#  psql --command "IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'user')\
#  THEN CREATE USER user WITH SUPERUSER ENCRYPTED PASSWORD 'password'; END IF;" &\
#  createdb main
