#!/usr/bin/env python3

import shutil
from mypi.config import WriteConfigEtc,StripComments,fn_root,fn_etc,md

md(fn_etc('mosquitto-int'))
shutil.copy2(fn_root('config/pki/root_ca_cert.pem'),fn_etc('mosquitto-int'))

tls_priv_pem = fn_etc('mosquitto-int','tls_priv.pem')
# TODO: create the key if missing
# openssl genrsa -out "${DIR_ROOT}/etc/mosquitto-int/tls_priv.pem" 2048
tls_cert_pem = fn_etc('mosquitto-int','tls_cert.pem')
# TODO: create the cert if missing

mosquitto_conf='''\
port 1883

listener 8883 0.0.0.0
certfile /etc/mosquitto/tls_cert.pem
keyfile  /etc/mosquitto/tls_priv.pem
cafile /etc/mosquitto/root_ca_cert.pem

log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous true
'''

WriteConfigEtc('mosquitto-int/mosquitto.conf',StripComments(mosquitto_conf))
