#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"

mkdir -p "${DIR_ROOT}/etc/mosquitto-int"
cp "${DIR_ROOT}/config/pki/root_ca_cert.pem" "${DIR_ROOT}/etc/mosquitto-int/"

if [[ ! -f "${DIR_ROOT}/etc/mosquitto-int/tls_priv.pem" ]]; then
  openssl genrsa -out "${DIR_ROOT}/etc/mosquitto-int/tls_priv.pem" 2048
fi

if [[ ! -f "${DIR_ROOT}/etc/mosquitto-int/tls_cert.pem" ]]; then
  true
fi

Config::WriteEtcStripped "mosquitto-int/mosquitto.conf" <<EOF
port 1883

listener 8883 0.0.0.0
certfile /etc/mosquitto/tls_cert.pem
keyfile  /etc/mosquitto/tls_priv.pem
cafile /etc/mosquitto/root_ca_cert.pem

log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous true
EOF
