#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"
DIR_THIS="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/docker.sh"

Docker::Rm mqtt-int

"${DIR_THIS}/create-config"

Service::Start mqtt-int /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

docker network connect mypi-internal mqtt-int