service:
  image: mqtt
  depends: []
  mount:
    - etc/mosquitto-int:/etc/mosquitto
  ports:
    - 8883:8883/tcp
    - 1883:1883/tcp
  command:
    - /usr/sbin/mosquitto 
    - -c
    - /etc/mosquitto/mosquitto.conf
  networks:
    - mypi-net
    - mypi-internal
