#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"

Service::Start iobroker /opt/iobroker_startup.sh
#Service::Start iobroker sleep 10000

 docker network connect mypi-internal iobroker