#!/usr/bin/env python3

import time

from mypi.config import GetConfig,WriteConfigEtc,StripComments
from mypi.fritzbox import get_external_ip

config = GetConfig()

dyndns = config['dyndns']
hostname = config['hostname']
public_ip = get_external_ip()

WriteConfigEtc('nsd/public_ip.txt',public_ip)

nsd_conf='''\
## NSD authoritative only DNS
## nsd.conf .:. https://calomel.org
## Primary or "Master" NSD server
#

server:
  # uncomment to specify specific interfaces to bind (default all).
  #  ip-address: 10.0.0.111

  # port to answer queries on. default is 53.
    port: 53

  # Number of NSD servers to fork.
    server-count: 1

  # listen only on IPv4 connections
    ip4-only: yes

  # don't answer VERSION.BIND and VERSION.SERVER CHAOS class queries
    hide-version: yes

  # identify the server (CH TXT ID.SERVER entry).
    identity: ""

  # The directory for zonefile: files.
    zonesdir: "/etc/nsd/zones"

# key:
#    name: "sec_key"
#    algorithm: hmac-md5
#    secret: "6KM6qiKfwfEpamEq72HQdA=="

remote-control:
    control-enable: yes
'''

for domain in config['domains']:
    domain_name = domain['name']
    nsd_conf += f'''\
zone:
    name: {domain_name}
    zonefile: {domain_name}
'''

WriteConfigEtc('nsd/nsd.conf',StripComments(nsd_conf))

for domain_config in config['domains']:
  domain = domain_config['name']
  if domain_config.get('intranet'):
    wildcard_entry='f*       CNAME   {hostname}.'
  else:
    wildcard_entry=f'*       IN A    {public_ip}'
  serial = int(time.time())
  WriteConfigEtc(f'nsd/zones/{domain}',f'''
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

$ORIGIN {domain}.
$TTL 60

@ IN SOA ns1.{domain}. admin.{domain}. (
        {serial:10}  ; serial number
        28800       ; Refresh
        7200        ; Retry
        600         ; Expire  (10 Minutes)
        60          ; Min TTL (1 Minute)
)
        NS      ns1.{domain}.
ns1     CNAME   {dyndns}.
{wildcard_entry}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

_acme-challenge 10 IN TXT NA

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
''')
