#!/bin/sh

set -e

echo "----- auth -----"
NSD_ZONE="$(cat "/etc/nsd/zones/${CERTBOT_DOMAIN}")"
NSD_ZONE="$(echo "${NSD_ZONE}" | grep -v _acme-challenge)"
NSD_ZONE="${NSD_ZONE}
_acme-challenge TXT ${CERTBOT_VALIDATION}"
echo "${NSD_ZONE}"
echo "${NSD_ZONE}" > "/etc/nsd/zones/${CERTBOT_DOMAIN}"
PID=$(cat /var/run/nsd/nsd.pid)
kill -HUP $PID
echo "----- auth -----"