#!/usr/bin/env python3

from mypi.config import GetConfig,WriteConfigEtc

config = GetConfig()

vsftpd_conf=f'''\
anonymous_enable=NO
dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES
xferlog_file=/dev/stdout
listen=YES
local_enable=YES
chroot_local_user=YES
allow_writeable_chroot=YES
write_enable=YES
local_umask=022
passwd_chroot_enable=yes
seccomp_sandbox=NO
pasv_enable=YES
pasv_address={config['private_ip']}
pasv_max_port=10100
pasv_min_port=10090
'''

WriteConfigEtc('vsftpd/vsftpd.conf',vsftpd_conf)
