service:
  image: esphome
  #privileged: true
  #pull: true
  depends: []
  mount:
    - /opt/mypi/data/home-assistant/esphome:/config
  env:
    - USERNAME=esphome
    - PASSWORD=ChangeMe
  dockerargs:
    #- --device=/dev/bus/usb:/dev/bus/usb:rwm
    - --hostname=esphome
    - '-u'
    - '1000:1000'
  networks:
    - mypi-internal
    - mypi-macvlan
