service:
  image: esphome
  depends: []
  mount:
    - /opt/mypi/data/home-assistant/esphome:/config
  env:
    - USERNAME=esphome
    - PASSWORD=ChangeMe
  dockerargs:
    - --hostname=esphome
    - '-u'
    - '1000:1000'
  networks:
    - mypi-internal
    - mypi-macvlan
