#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))+"/lib/python")

from mypi.config import GetConfig,WriteYamlEtc

config = GetConfig()

result = {}
result['hosts'] = []
result['certs'] = []

for domain in config['domains']:
    domainName = domain['name']
    print(domainName, file=sys.stderr)

    entry = {}
    entry['cert']='/etc/letsencrypt/live/'+domainName+'/fullchain.pem'
    entry['key']='/etc/letsencrypt/live/'+domainName+'/privkey.pem'
    result['certs'].append(entry)

    if not 'hosts' in domain:
        continue
    for host in domain['hosts']:
        hostName = host['name']
        print("  "+hostName,file=sys.stderr)
        # if not 'gateway' in host:
        #     continue
        # gateway = host['gateway']
        if not 'uri' in host:
            continue
        uri = host['uri']
        entry={}
        entry['name']=hostName+"."+domainName
        entry['target']=uri
        if 'insecure' in host:
            entry['insecure']=host['insecure']
        if 'headers' in host:
            entry['insecure'] = host['headers']

        entry['mode'] = 'router'
        if 'router' in host:
            entry['target'] = 'mypi-router:8080'
        elif uri.startswith('http://'):
            entry['target'] = uri[7:]

        result['hosts'].append(entry)

WriteYamlEtc('mypi-gateway/gateway.yml',result)
