#!/usr/bin/env bash

set -e

DIR_THIS="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

"${DIR_THIS}/create-config"

docker stop mypi-gateway || true
docker rm mypi-gateway || true

"${DIR_THIS}/start" "$@"
