#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"

Service::Start mypi-gateway \
  --http-port=10080 --https-port=10443 \
  /etc/mypi-gateway/gateway.yml
