service:
  image: ghcr.io/home-assistant/home-assistant:stable
  depends: []
  mount:
    - /opt/mypi/data/home-assistant:/config
  dockerargs:
    - --hostname=home-assistant
  networks:
    - mypi-internal
    - mypi-macvlan
