#!/usr/bin/env python3

import shutil
from mypi.config import GetConfig,WriteConfigEtc,StripComments,fn_root,fn_etc,md

config = GetConfig()
dyndns = config['dyndns']
domain = config['domains'][0]['name']

md(fn_etc('mosquitto'))
shutil.copy2(fn_root('config/pki/root_ca_cert.pem'),fn_etc('mosquitto'))

mosquitto_conf=f'''\
port 1883

listener 8883 0.0.0.0
certfile /etc/letsencrypt/live/{domain}/cert.pem
cafile /etc/letsencrypt/live/{domain}/chain.pem
keyfile /etc/letsencrypt/live/{domain}/privkey.pem

#persistence_file mosquitto.db
#log_dest syslog
log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous false
password_file /etc/mosquitto/passwd

connection bridge-to-mqtt-int
address mqtt-int:8883
bridge_insecure true
bridge_cafile /etc/mosquitto/root_ca_cert.pem
remote_clientid bridge-mqtt-ext
start_type automatic
topic # out 2 owntracks/ owntracks/
'''

WriteConfigEtc('mosquitto/mosquitto.conf',StripComments(mosquitto_conf))
