service:
  image: mypi-smarthome
  depends: []
  mount:
    - config/mypi.yml:/opt/mypi/config/mypi.yml
    - config/pki:/opt/mypi/config/pki
    - etc/mypi-smarthome
  ports: []
  command:
    - "--mqtt=mqtt-int"
    - "/etc/mypi-smarthome/smarthome.yml"

