service:
  image: mypi-router
  depends: []
  mount:
    - etc/letsencrypt
    - etc/mypi-auth/clients/mypi-router.yml:/opt/mypi/etc/mypi-auth/clients/mypi-router.yml
    - etc/mypi-router
    - /opt/mypi/config/mypi.yml:/opt/mypi/config/mypi.yml
  ports:
    - 10080:10080/tcp
    - 10443:10443/tcp
    - 10444:10444/tcp
  command:
    - --http-port=10080
    - --https-port=10443
    - /etc/mypi-router/router.yml
  networks:
    - mypi-net
    - mypi-internal/-1