service:
  image: mypi-auth
  depends: []
  mount:
  - config/mypi.yml:/opt/mypi/config/mypi.yml
  - etc/mypi-auth:/opt/mypi/etc/mypi-auth
  ports: []
  command:
    - --mypi-root=/opt/mypi
    - --port=8080