service:
  image: mypi-auth
  depends: []
  mount:
  - config/mypi.yml:/opt/mypi/config/mypi.yml
  - etc/auth:/opt/mypi/etc/auth
  - etc/users.yml:/opt/mypi/etc/users.yml
  ports: []
  command:
    - --mypi-root=/opt/mypi
    - --port=8080