#!/usr/bin/env bash

set -e

FILTER="${1}"

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"

dyndns="$(Config::Get ".config.dyndns")"

if [[ -n "${dyndns}" ]]; then
    if [[ -n "${FILTER}" && "${FILTER}" != "${dyndns}" ]]; then
        echo "Ignoring: ${dyndns}"
    else
        echo "Request certificate for: ${dyndns}"
        echo
        Service::Run certbot certonly\
            --manual -n \
            --preferred-challenges=http \
            --agree-tos \
            --manual-public-ip-logging-ok \
            -d "${dyndns}" \
            --manual-auth-hook=/services/certbot/hooks/http-auth \
            --manual-cleanup-hook=/services/certbot/hooks/http-cleanup
    fi
fi

for ((i = 0 ;  ; i++)); do
    domain="$(Config::Get ".config.domains[${i}].name")"
    if [[ -z "${domain}" ]]; then
        break
    fi
    if [[ -n "${FILTER}" && "${FILTER}" != "${domain}" ]]; then
        echo "Ignoring: *.${domain}"
        continue
    fi
    echo "Request certificate for: *.${domain}"
    echo
    Service::Run certbot certonly\
        --manual -n \
        --preferred-challenges=dns \
        --agree-tos \
        --manual-public-ip-logging-ok \
        -d "*.${domain}" \
        --manual-auth-hook=/services/certbot/hooks/dns-auth \
        --manual-cleanup-hook=/services/certbot/hooks/dns-cleanup
done
