#!/usr/bin/env python3

import sys
from mypi.config import GetConfig
from mypi.service import Service
from mypi.console.powerline import Powerline,c

service = Service("certbot")

config = GetConfig()
dyndns = config.get('dyndns')
if dyndns:
    with Powerline() as p:
        p.segment(bg=c.rgb6(0,0,5),fg=c.rgb6(5,5,0),text=dyndns)
    rc = service.run('certonly', '--manual', '-n', '--preferred-challenges=http',
            '--agree-tos', '--manual-public-ip-logging-ok',
            '-d', dyndns,
            '--manual-auth-hook=/services/certbot/hooks/http-auth',
            '--manual-cleanup-hook=/services/certbot/hooks/http-cleanup')
    if rc != 0:
        sys.exit(rc)

for domain_info in config.get('domains'):
    domain = domain_info.get('name')
    if not domain:
        continue
    with Powerline() as p:
        p.segment(bg=c.rgb6(0,0,5),fg=c.rgb6(5,5,0),text=domain)
    rc = service.run('certonly', '--manual', '-n', '--preferred-challenges=dns',
            '--agree-tos', '--manual-public-ip-logging-ok',
            '-d', '*.'+domain,
            '--manual-auth-hook=/services/certbot/hooks/dns-auth',
            '--manual-cleanup-hook=/services/certbot/hooks/dns-cleanup')
    if rc != 0:
        sys.exit(rc)
