#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"

Service::Run certbot renew # --force-renewal