#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"

URL="$(Config::Get ".config.webcams[0].url")"

Service::Start videostreamer -input "${URL}" -port 20042 -format rtsp
