#!/usr/bin/env python3

import sys
import os

from mypi.config import GetConfig,WriteYamlEtc,ReadYamlEtc

config = GetConfig()

ccu = ReadYamlEtc('ccu/credentials.yml')


result = {}
result['ccu']={}
result['ccu']['uri']='http://ccu.mypi-internal'
result['ccu']['username']=ccu['ccu']['username']
result['ccu']['password']=ccu['ccu']['password']
result['mqtt']={}
result['mqtt']['uri']='ssl://mqtt-int:8883'
result['mqtt']['client_id']='ccu2mqtt-int'

WriteYamlEtc('mypi-ccu2mqtt/config.yml',result)
