#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

source "${DIR_ROOT}/scripts/lib/docker.sh"

Docker::Stop mypi-api

killall -9 socat

socat TCP-LISTEN:8080,reuseaddr,fork,bind=172.17.0.1 TCP:127.0.0.1:8080 &
socat TCP-LISTEN:11111,reuseaddr,fork,bind=localhost UNIX-CONNECT:/var/run/docker.sock