#!/usr/bin/env bash

set -e
DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

source "${DIR_ROOT}/scripts/lib/docker.sh"
source "${DIR_ROOT}/scripts/lib/config.sh"

Docker::ImageCreate tools
Docker::ImageCreate tools-docker
Docker::ImageCreate golang
Docker::ImageCreate mypi-api