#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

source "${DIR_ROOT}/scripts/lib/docker.sh"

docker run \
        -i \
        --name    vue \
        --volume  "${DIR_ROOT}/scripts:${DIR_ROOT}/scripts" \
        --volume  "${DIR_ROOT}/web/login-app:${DIR_ROOT}/web/login-app" \
        --publish 127.0.0.1:8080:8080 \
        "$(Docker::ImageName nodejs)" \
        ash -c "
cd '${DIR_ROOT}/web/login-app'
npm run serve
"
