#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

mkdir -p "${DIR_ROOT}/.tmp"

tmux_is_running()
{
    tmux list-sessions -F '#{session_name}' | grep "^${1}\$" &>/dev/null
}

tmux_session_name()
{
    echo "mypi-vue-${1}"
}

tmux_start()
{
    local SESSION
    SESSION="$(tmux_session_name "${1}")"
    if ! tmux_is_running "${SESSION}"; then
        tmux new -s "${SESSION}" -d "cd \"${DIR_ROOT}/web/${1}\"; PORT=8888 npm run serve"
    fi
}

tmux_stop()
{
    tmux kill-session -t "$(tmux_session_name "${1}")"
}

tmux_attach()
{
    tmux attach -t "$(tmux_session_name "${1}")"
}

CMD="${1}"
APP="${2}"

echo "CMD: ${CMD}"
echo "APP: ${APP}"

if [[ -z "${APP}" ]] || [[ ! -d "${DIR_ROOT}/web/${APP}" ]]; then
    echo "'${APP}' is not a valid vue app"
    exit 1
fi

case "${CMD}" in
    start)
        tmux_start "${APP}"
        ;;
    stop)
        tmux_stop "${APP}"
        ;;
    attach)
        tmux_attach "${APP}"
        ;;
esac


