#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))+"/lib/python")

from mypi.config import GetConfig,WriteYamlEtc,ReadYamlEtc

config = GetConfig()
