#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"
DIR_THIS="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/service.sh"
# shellcheck source=/dev/null
source "${DIR_ROOT}/scripts/lib/config.sh"

"${DIR_THIS}/create-config"

Service::Start mypi-smarthome  --mypi-root=/opt/mypi --mqtt=mqtt-int /etc/mypi-smarthome/smarthome.yml
