#!/usr/bin/env python3

import sys
import os

from mypi.config import GetConfig,WriteYamlEtc,ReadYamlEtc

config = GetConfig()

auth = ReadYamlEtc('auth/clients/mypi-router.yml')

primaryDomain = config['domains'][0]['name']

result = {}
result['hosts'] = []
result['certs'] = []
result['auth']= {}
result['auth']['client_id']=auth['client_id']
result['auth']['uri']='https://auth.' + primaryDomain
result['auth']['client_secret']=auth['client_secret']
result['auth']['server_key']=auth['server_key']
result['auth']['secret']=auth['secret']

for domain in config['domains']:
    domainName = domain['name']
    print(domainName, file=sys.stderr)

    entry = {}
    entry['cert']='/etc/letsencrypt/live/'+domainName+'/fullchain.pem'
    entry['key']='/etc/letsencrypt/live/'+domainName+'/privkey.pem'
    result['certs'].append(entry)

    if not 'hosts' in domain:
        continue
    for host in domain['hosts']:
        hostName = host['name']
        print("  "+hostName,file=sys.stderr)
        # if not 'gateway' in host:
        #     continue
        # gateway = host['gateway']
        if not 'target' in host:
            continue
        target = host['target']
        entry={}
        entry['name']=hostName+"."+domainName
        entry['target']=target
        if 'insecure' in host:
            entry['insecure']=host['insecure']
        if 'headers' in host:
            entry['insecure'] = host['headers']

        if 'mode' in host:
            entry['mode'] = host['mode']
        else:
            entry['mode'] = 'http'

        if 'options' in host:
            entry['options'] = host['options']

        result['hosts'].append(entry)

WriteYamlEtc('mypi-router/router.yml',result)
