#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))+"/lib/python")

from mypi.config import GetConfig,WriteYamlEtc

config = GetConfig()

result = {}
result['routes'] = []
for domain in config['domains']:
    domainName = domain['name']
    if not 'hosts' in domain:
        continue
    for host in domain['hosts']:
        hostName = host['name']
        if not 'router' in host:
            continue
        router = host['router']
        if not 'uri' in host:
            continue
        uri = host['uri']
        entry={}
        entry['hostname']=hostName+"."+domainName
        entry['target']=uri
        if 'insecure' in host:
            entry['insecure']=host['insecure']
        if 'headers' in host:
            entry['insecure']=host['headers']
        result['routes'].append(entry)

WriteYamlEtc('mypi-router/router.yml',result)
